# Site settings
title: Austin Pray
site_title: Austin Pray · Engineering Manager @ Mixpanel
email: austin@austinpray.com
description: >
  Austin loves building teams, tools, and platforms that empower others to do
  their best work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://austinpray.com" # the base hostname & protocol for your site
github_username:  austinpray
work_github_username:  austinpray-mixpanel
linkedin: "https://linkedin.com/in/austin-pray"

repo_baseurl: "https://github.com/austinpray/austinpray.com/blob/gh-pages/"
repo_editurl: "https://github.com/austinpray/austinpray.com/edit/gh-pages/"

# Build settings
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope: 
      path: ""
      type: posts
    values:
      layout: post
      author: "Austin Pray"

exclude:
  - .claude-user
  - .devcontainer
  - .editorconfig
  - .github
  - .gitignore
  - .vscode
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - justfile
  - README.md
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
